stringtie_read_length: 50
stringtie_strand_flag: ''
# '--rf'    Assumes a stranded library fr-firststrand
# '--fr'    Assumes a stranded library fr-secondstrand
# ''        Leave blank if unstranded 

dirs:
  input: test/inputs
  output: ../outputs
  reference: ../reference/mm10_ercc

genome_reference:
  fasta: mm10_ercc.fa
  gtf: mm10_ercc.gencode.vM17.annotation.exon.gtf
  star_genome_dir: star_genome

samples:
  SampleA:
    - SampleA.R1.fastq.gz
    - SampleA.R2.fastq.gz
  SampleB:
    - SampleB.R1.fastq.gz
    - SampleB.R2.fastq.gz
# - SampleC
