stringtie:
  read_length: 50
  #strand_flag
  # '--rf'    Assumes a stranded library fr-firststrand, e.g. Trueseq
  # '--fr'    Assumes a stranded library fr-secondstrand
  # ''        Leave blank if unstranded
  strand_flag: ''

dirs:
  input: test/inputs
  output: ../outputs
  reference: ../reference/mm10_ercc

genome_reference:
  fasta: mm10_ercc.fa
  gtf: mm10_ercc.gencode.vM17.annotation.exon.gtf
  star_genome_dir: star_genome

samples:
  SampleA:
    - SampleA.R1.fastq.gz
    - SampleA.R2.fastq.gz
  SampleB:
    - SampleB.R1.fastq.gz
    - SampleB.R2.fastq.gz
# - SampleC
